# Site settings
title: Raquib-ul-Alam
email: alam.kanak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Android developer and fan of Breaking Bad. Enjoy 'good looking' food. Don't mind the taste.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alamkanak.me" # the base hostname & protocol for your site
twitter_username: alamkanak
github_username:  alamkanak
googleplus_username: AlamKanak
linkedin_url: http://bd.linkedin.com/in/alamkanak
pinterest_username: alamkanak
behance_username: alamkanak
facebook_username: alam.kanak

# Build settings
markdown: kramdown

# Permalink

# Collections
collections:
 portfolios:
  output: true
  permalink: /portfolio/:title/
